<?php
// ============================================================
//  REGISTRAR/MASTERLIST.PHP
//  Masterlist generator (by course, year, section — max 50/section)
// ============================================================

require_once __DIR__ . '/../shared/security_headers.php';
require_once __DIR__ . '/../shared/session_config.php';

if (empty($_SESSION['user_id'])) {
    header('Location: ../login.php');
    exit;
}

require_once __DIR__ . '/../shared/database.php';
require_once __DIR__ . '/../shared/functions.php';

$db = Database::getInstance();
$maxPerSection = defined('MAX_STUDENTS_PER_SECTION') ? (int) MAX_STUDENTS_PER_SECTION : 50;

$filterCourse = isset($_GET['course']) ? trim((string) $_GET['course']) : '';
$filterYear = isset($_GET['year_level']) ? trim((string) $_GET['year_level']) : '';

$sql = "SELECT * FROM students WHERE 1=1";
$params = [];
if ($filterCourse !== '') {
    $sql .= " AND TRIM(course) = ?";
    $params[] = $filterCourse;
}
if ($filterYear !== '' && is_numeric($filterYear)) {
    $sql .= " AND year_level = ?";
    $params[] = (int) $filterYear;
}
$sql .= " ORDER BY TRIM(course) ASC, COALESCE(year_level, 0) ASC, section ASC, last_name ASC, first_name ASC";

$students = $db->fetchAll($sql, $params);
$groups = groupStudentsForMasterlist($students);

$courses = $db->fetchAll(
    "SELECT DISTINCT TRIM(course) AS course FROM students
     WHERE course IS NOT NULL AND TRIM(course) != ''
     ORDER BY course"
);
$years = $db->fetchAll(
    "SELECT DISTINCT year_level FROM students WHERE year_level IS NOT NULL ORDER BY year_level"
);

$page_title = 'Masterlist';
$APP_ROOT = '../';
$ACTIVE_NAV = 'masterlist';
$assignedSuccess = isset($_GET['assigned']) && $_GET['assigned'] === '1';

include '../includes/header.php';
include '../includes/sidebar.php';
?>

<main class="main">
    <header class="header">
        <div class="title">
            <h1>Masterlist</h1>
            <p>Auto-generated by course, year level, and section (max <?= (int) $maxPerSection ?> students per section)</p>
        </div>
        <div class="header-actions">
            <button type="button" class="btn btn-secondary" id="btnAutoAssign" title="Assign Section A, B, C… per course and year (<?= (int) $maxPerSection ?> max each)">
                <i class="fas fa-wand-magic-sparkles"></i> Auto-assign sections
            </button>
            <button class="btn btn-secondary" onclick="window.print()">
                <i class="fas fa-print"></i> Print
            </button>
            <button class="btn btn-primary" onclick="exportCSV()">
                <i class="fas fa-file-csv"></i> Export CSV
            </button>
        </div>
    </header>

    <?php if ($assignedSuccess): ?>
        <div class="card" style="margin-bottom: 16px; padding: 12px 16px; background: #ecfdf5; border: 1px solid #a7f3d0; color: #065f46;">
            <i class="fas fa-check-circle"></i> Sections updated. Each course/year block now has up to <?= (int) $maxPerSection ?> students per section.
        </div>
    <?php endif; ?>

    <div class="card" style="margin-bottom: 16px;">
        <form method="get" class="form-row" style="display: flex; flex-wrap: wrap; gap: 12px; align-items: flex-end; padding: 16px;">
            <div class="form-group" style="min-width: 160px;">
                <label class="form-label" for="filterCourse">Course</label>
                <select name="course" id="filterCourse" class="form-control">
                    <option value="">All courses</option>
                    <?php foreach ($courses as $row): ?>
                        <option value="<?= htmlspecialchars($row['course']) ?>" <?= $filterCourse === $row['course'] ? 'selected' : '' ?>>
                            <?= htmlspecialchars($row['course']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group" style="min-width: 120px;">
                <label class="form-label" for="filterYear">Year level</label>
                <select name="year_level" id="filterYear" class="form-control">
                    <option value="">All years</option>
                    <?php foreach ($years as $row): ?>
                        <option value="<?= (int) $row['year_level'] ?>" <?= $filterYear === (string) $row['year_level'] ? 'selected' : '' ?>>
                            Year <?= (int) $row['year_level'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <button type="submit" class="btn btn-primary"><i class="fas fa-filter"></i> Filter</button>
            <?php if ($filterCourse !== '' || $filterYear !== ''): ?>
                <a href="masterlist.php" class="btn btn-light">Clear</a>
            <?php endif; ?>
        </form>
    </div>

    <div id="masterlistContent">
        <?php if (empty($groups)): ?>
            <div class="card">
                <p class="text-center py-12 text-gray-500" style="padding: 48px; text-align: center; color: #64748b;">No students found</p>
            </div>
        <?php else: ?>
            <?php foreach ($groups as $group):
                $count = count($group['students']);
                $overCap = $count > $maxPerSection;
                $sectionTitle = htmlspecialchars($group['course']) . ' — Year ' . htmlspecialchars($group['year_level'])
                    . ' — Section ' . htmlspecialchars($group['section']);
            ?>
                <div class="card masterlist-section-block" style="margin-bottom: 16px;" data-course="<?= htmlspecialchars($group['course']) ?>" data-section="<?= htmlspecialchars($group['section']) ?>">
                    <div style="padding: 14px 16px; border-bottom: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 8px;">
                        <h2 style="margin: 0; font-size: 15px; font-weight: 700; color: #0f172a;">
                            <i class="fas fa-users" style="color: #2563eb; margin-right: 8px;"></i><?= $sectionTitle ?>
                        </h2>
                        <span class="badge <?= $overCap ? 'badge-warning' : 'badge-success' ?>" style="font-size: 12px;">
                            <?= $count ?> / <?= (int) $maxPerSection ?> students
                            <?php if ($overCap): ?> — over capacity<?php endif; ?>
                        </span>
                    </div>
                    <div style="overflow-x: auto;">
                        <table class="masterlist-table" style="width: 100%; border-collapse: collapse; font-size: 13px;">
                            <thead>
                                <tr style="background: #1a2d4a; color: white;">
                                    <th style="padding: 10px 12px; text-align: left;">#</th>
                                    <th style="padding: 10px 12px; text-align: left;">Student ID</th>
                                    <th style="padding: 10px 12px; text-align: left;">Name</th>
                                    <th style="padding: 10px 12px; text-align: left;">Course</th>
                                    <th style="padding: 10px 12px; text-align: left;">Year</th>
                                    <th style="padding: 10px 12px; text-align: left;">Section</th>
                                    <th style="padding: 10px 12px; text-align: left;">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i = 1; foreach ($group['students'] as $student): ?>
                                    <tr style="border-bottom: 1px solid #e2e8f0;">
                                        <td style="padding: 8px 12px;"><?= $i++ ?></td>
                                        <td style="padding: 8px 12px;"><?= htmlspecialchars($student['student_number']) ?></td>
                                        <td style="padding: 8px 12px;"><?= htmlspecialchars($student['last_name']) ?>, <?= htmlspecialchars($student['first_name']) ?></td>
                                        <td style="padding: 8px 12px;"><?= htmlspecialchars($student['course'] ?? 'N/A') ?></td>
                                        <td style="padding: 8px 12px;"><?= htmlspecialchars($student['year_level'] ?? 'N/A') ?></td>
                                        <td style="padding: 8px 12px;"><?= htmlspecialchars($student['section'] ?? '—') ?></td>
                                        <td style="padding: 8px 12px;">
                                            <span class="badge badge-<?= $student['status'] === 'active' ? 'success' : 'warning' ?>">
                                                <?= ucfirst($student['status'] ?? 'Active') ?>
                                            </span>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

    <div class="card" style="margin-top: 8px;">
        <div class="table-footer">
            <div class="info-text">
                Total: <strong><?= count($students) ?></strong> students in <strong><?= count($groups) ?></strong> section group(s)
            </div>
        </div>
    </div>
</main>

<script>
const MAX_PER_SECTION = <?= (int) $maxPerSection ?>;

document.getElementById('btnAutoAssign')?.addEventListener('click', async function () {
    if (!confirm('Assign sections for all students by course and year level? Each section will have at most ' + MAX_PER_SECTION + ' students (A, B, C…).')) {
        return;
    }
    const btn = this;
    btn.disabled = true;
    btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Assigning…';
    try {
        const response = await fetch('../api/masterlist.php', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ action: 'assign_sections', max_per_section: MAX_PER_SECTION })
        });
        const data = await response.json();
        if (!data.success) {
            alert(data.message || 'Failed to assign sections.');
            return;
        }
        const params = new URLSearchParams(window.location.search);
        params.set('assigned', '1');
        window.location.href = 'masterlist.php?' + params.toString();
    } catch (err) {
        alert('Network error. Please try again.');
    } finally {
        btn.disabled = false;
        btn.innerHTML = '<i class="fas fa-wand-magic-sparkles"></i> Auto-assign sections';
    }
});

function exportCSV() {
    let csv = 'Student ID,Name,Course,Year,Section,Status\n';
    document.querySelectorAll('#masterlistContent .masterlist-table tbody tr').forEach(row => {
        const cols = row.querySelectorAll('td');
        if (cols.length < 7) return;
        const escape = (v) => '"' + String(v).replace(/"/g, '""') + '"';
        csv += [
            escape(cols[1].textContent.trim()),
            escape(cols[2].textContent.trim()),
            escape(cols[3].textContent.trim()),
            escape(cols[4].textContent.trim()),
            escape(cols[5].textContent.trim()),
            escape(cols[6].textContent.trim())
        ].join(',') + '\n';
    });

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'masterlist-by-section.csv';
    a.click();
    window.URL.revokeObjectURL(url);
}
</script>

<style>
@media print {
    .sidebar, .header-actions, .form-row, .btn { display: none !important; }
    .masterlist-section-block { break-inside: avoid; page-break-inside: avoid; }
}
</style>

<?php include '../includes/footer.php'; ?>
